version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: web3
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Source/taikhoan/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Source:/var/www/html
    networks:
      - webnet
    restart: always

  nginx:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Source:/var/www/html:ro
    networks:
      - webnet
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  webnet:
    driver: bridge