version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: web3
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Source/taikhoan/database.sql:/docker-entrypoint-initdb.d/database.sql  # MySQL sẽ tự động import
    networks:
      - webnet

  php:
    build: .
    depends_on:
      - db
    volumes:
      - ./Source:/var/www/html
    networks:
      - webnet
    entrypoint: /bin/sh -c "until nc -z -v -w30 db 3306; do echo 'Waiting for MySQL...'; sleep 5; done; php-fpm"  # Chờ MySQL sẵn sàng

  nginx:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Source:/var/www/html:ro
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
